### PR TITLE
clarify intentions of usage in the README (fix #36)

### LINKED ISSUE #36: Update README -- No longer an installation "the Amber way"
``grunt-init-amber`` does not need to be installed directly by the user at all.

Update READE.me to reflect this more **clearly**. 

Simply state

``grunt-init-amber`` is a component which is automatically installed when you install ``amber-cli``.

And then refer to the main amber installation [README](https://github.com/amber-smalltalk/amber/blob/master/README.md).

@herby : you can assign this to me.

### PR DESCRIPTION
**Pull request by mkroehnert**
This should fix #36

### CODE REVIEW

**Comment by mkroehnert** [comment]
Now, all is one.

**Comment by herby** [comment]
@hhzl Looks good?

**Comment by hhzl** [comment]
Title for Amber way is much clearer. And the text states newly that ``amber-cli`` is to be preferred.

The link to [https://www.npmjs.org/package/amber-cli](https://www.npmjs.org/package/amber-cli) leads to a page which gives no new information. Either use [amber-cli](https://github.com/amber-smalltalk/amber) instead or fix the README in https://www.npmjs.org/package/amber-cli.

Avoid the proliferation of incomplete amber-cli instructions, in particular the ``sudo`` issue which causes problems in quite a number of cases and just refer to the general [Amber README](https://github.com/amber-smalltalk/amber). This will help to reduce the documentation effort because the information is not scattered in different places.

**Comment by mkroehnert** [comment]
@hhzl please check the diff again.
What you mention has already been removed (hint: red lines in the diff view).

**Comment by hhzl** [comment]
@mkroehnert OK, fine, got it. And https://www.npmjs.com/package/amber#getting-amber now has a description (i.e the README of the current release 0.14.3. When I checked npmjs.com/ two hours ago it was still missing. I assume you fixed it.

**Comment by herby** [comment]
It's get updated when `npm publish` is run afaict, so you @hhzl probably had a cached version.

Anyway, it seems now all is fine and this can be merged, is it?

Hannes Hirzel wrote:

**Pull request merged**
