### PR TITLE
Add Silk as one of web manipulating possibilities

### PR DESCRIPTION
**Pull request by herby**

### CODE REVIEW

**Comment by herby** [comment]
@amber-smalltalk/owners @amber-smalltalk/contributors @amber-smalltalk/helios @amber-smalltalk/documentation What do you think of this? Should this other alternative be included in the new project template?

**Comment by mkroehnert** [comment]
I have no strong opinion on this.

If it is included by default it should come with instructions on how to remove it again (if someone does not want it).
Otherwise it should probably come with a prompt asking if it should be included.

**Comment by herby** [comment]
The same goes for others - some people don't want to use internal 'Web' as well and are fine with just the jQuery wrapper (or they even do not want jQuery at all). Added it as #38.

**Comment by hhzl** [comment]
I am fine with adding Silk. I'll use it.

**Pull request merged**
